
package proxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.3
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ws_banque", targetNamespace = "http://ws/", wsdlLocation = "http://127.0.0.1:8080/ws_banque?wsdl")
public class WsBanque_Service
    extends Service
{

    private static final URL WSBANQUE_WSDL_LOCATION;
    private static final WebServiceException WSBANQUE_EXCEPTION;
    private static final QName WSBANQUE_QNAME = new QName("http://ws/", "ws_banque");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8080/ws_banque?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSBANQUE_WSDL_LOCATION = url;
        WSBANQUE_EXCEPTION = e;
    }

    public WsBanque_Service() {
        super(__getWsdlLocation(), WSBANQUE_QNAME);
    }

    public WsBanque_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSBANQUE_QNAME, features);
    }

    public WsBanque_Service(URL wsdlLocation) {
        super(wsdlLocation, WSBANQUE_QNAME);
    }

    public WsBanque_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSBANQUE_QNAME, features);
    }

    public WsBanque_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsBanque_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WsBanque
     */
    @WebEndpoint(name = "ws_banquePort")
    public WsBanque getWsBanquePort() {
        return super.getPort(new QName("http://ws/", "ws_banquePort"), WsBanque.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsBanque
     */
    @WebEndpoint(name = "ws_banquePort")
    public WsBanque getWsBanquePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws/", "ws_banquePort"), WsBanque.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSBANQUE_EXCEPTION!= null) {
            throw WSBANQUE_EXCEPTION;
        }
        return WSBANQUE_WSDL_LOCATION;
    }

}
